"use client";

import { useMemo, useState } from "react";
import { AlertTriangle, ArrowRight, BarChart3, Bookmark, BriefcaseBusiness, Building2, Check, ChevronDown, Columns3, EyeOff, FileText, Gauge, MapPin, MessageCircle, RotateCcw, School, SlidersHorizontal, Sparkles, Target, UserRound, Users } from "lucide-react";
import { FormActions, UiModal } from "@/components/ui-modal";
import { initialBuyerProfiles, type BuyerProfile } from "@/lib/buyer-data";
import { initialProperties, type PropertyRecord } from "@/lib/property-data";
import { rankBuyerProperties, scoreBuyerProperty, type ExplainableMatch, type FitCategory } from "@/lib/matching-engine";

type Props={onReport:()=>void;notify:(message:string)=>void};
type Direction="Buyer → Properties"|"Property → Buyers";
const number=new Intl.NumberFormat("en-US",{maximumFractionDigits:0});

export function MatchingEpic({onReport,notify}:Props){
  const [direction,setDirection]=useState<Direction>("Buyer → Properties");
  const [buyerId,setBuyerId]=useState(initialBuyerProfiles[0].id);
  const [propertyId,setPropertyId]=useState(initialProperties[0].id);
  const [minimum,setMinimum]=useState(0);
  const [bestOnly,setBestOnly]=useState(false);
  const [states,setStates]=useState<Record<string,Partial<ExplainableMatch>>>({});
  const [matrix,setMatrix]=useState<ExplainableMatch|null>(null);
  const [deal,setDeal]=useState<ExplainableMatch|null>(null);
  const [overriding,setOverriding]=useState<ExplainableMatch|null>(null);
  const [pitch,setPitch]=useState<{buyer:BuyerProfile;property:PropertyRecord;match:ExplainableMatch}|null>(null);
  const [showDealToClient,setShowDealToClient]=useState(true);
  const [compare,setCompare]=useState<string[]>([]);
  const buyer=initialBuyerProfiles.find((item)=>item.id===buyerId)??initialBuyerProfiles[0];
  const property=initialProperties.find((item)=>item.id===propertyId)??initialProperties[0];
  const buyerMatches=useMemo(()=>rankBuyerProperties(buyer,initialProperties).map((item)=>({...item,...states[item.id]})),[buyer,states]);
  const propertyMatches=useMemo(()=>initialBuyerProfiles.map((candidate)=>{const base=scoreBuyerProperty(candidate,property);return{buyer:candidate,match:{...base,...states[base.id]}};}).sort((a,b)=>b.match.score-a.match.score),[property,states]);
  const visibleBuyerMatches=buyerMatches.filter((item)=>!item.hidden&&item.score>=minimum).filter((_,index)=>!bestOnly||index<3);
  const visiblePropertyMatches=propertyMatches.filter((item)=>!item.match.hidden&&item.match.score>=minimum).filter((_,index)=>!bestOnly||index<3);
  function patch(match:ExplainableMatch,next:Partial<ExplainableMatch>){setStates((all)=>({...all,[match.id]:{...all[match.id],...next}}));}
  function report(match?:ExplainableMatch){notify(`Report setup opened${match?` · ${match.score}% buyer fit`:""}${showDealToClient?" · deal score included":" · deal score hidden"}`);onReport();}
  function toggleCompare(match: ExplainableMatch) { setCompare((items)=>items.includes(match.propertyId)?items.filter((id)=>id!==match.propertyId):items.length>=5?items:[...items,match.propertyId]); }
  return <div className="module-stack matching-epic">
    <div className="matching-direction">{(["Buyer → Properties","Property → Buyers"] as Direction[]).map((item)=><button key={item} className={direction===item?"active":""} onClick={()=>setDirection(item)}>{item==="Buyer → Properties"?<Target/>:<Users/>}{item}<span>{item==="Buyer → Properties"?"Recommend inventory":"Find likely buyers"}</span></button>)}</div>
    <section className="matching-control-bar"><div><span>{direction==="Buyer → Properties"?"SELECT BUYER":"SELECT PROPERTY"}</span>{direction==="Buyer → Properties"?<label><UserRound/><select value={buyerId} onChange={(event)=>setBuyerId(event.target.value)}>{initialBuyerProfiles.map((item)=><option value={item.id} key={item.id}>{item.name} · {item.persona}</option>)}</select><ChevronDown/></label>:<label><Building2/><select value={propertyId} onChange={(event)=>setPropertyId(event.target.value)}>{initialProperties.map((item)=><option value={item.id} key={item.id}>{item.title}</option>)}</select><ChevronDown/></label>}</div><label className="minimum-score"><span>MINIMUM SCORE · {minimum}%</span><input type="range" min="0" max="90" step="10" value={minimum} onChange={(event)=>setMinimum(Number(event.target.value))}/></label><button className={bestOnly?"active":""} onClick={()=>setBestOnly(!bestOnly)}><SlidersHorizontal/>Best 3 only</button><button className={showDealToClient?"active":""} onClick={()=>setShowDealToClient(!showDealToClient)}>{showDealToClient?<Gauge/>:<EyeOff/>}Client deal score</button></section>
    {direction==="Buyer → Properties"?<BuyerRecommendations buyer={buyer} matches={visibleBuyerMatches} states={states} compare={compare} showDealToClient={showDealToClient} onMatrix={setMatrix} onDeal={setDeal} onOverride={setOverriding} onPatch={patch} onCompare={toggleCompare} onPitch={(property,match)=>setPitch({buyer,property,match})} onReport={report} notify={notify}/>:<PropertyBuyers property={property} matches={visiblePropertyMatches} onMatrix={setMatrix} onOverride={setOverriding} onPatch={patch} onPitch={setPitch} onReport={report}/>} 
    {direction==="Buyer → Properties"&&compare.length>=2&&<CompareTray properties={initialProperties.filter((item)=>compare.includes(item.id))} onClear={()=>setCompare([])} onReport={()=>report()} />} 
    {matrix&&<FitMatrixModal match={matrix} buyer={initialBuyerProfiles.find((item)=>item.id===matrix.buyerId)!} property={initialProperties.find((item)=>item.id===matrix.propertyId)!} onClose={()=>setMatrix(null)} onReport={()=>report(matrix)}/>} 
    {deal&&<DealScoreModal match={deal} property={initialProperties.find((item)=>item.id===deal.propertyId)!} visibleToClient={showDealToClient} onVisibility={()=>setShowDealToClient(!showDealToClient)} onClose={()=>setDeal(null)} onReport={()=>report(deal)}/>} 
    {overriding&&<OverrideModal match={overriding} onClose={()=>setOverriding(null)} onSave={(score,reason)=>{patch(overriding,{score,overridden:true,overrideReason:reason});setOverriding(null);notify("Broker score override saved and logged");}} onReset={()=>{patch(overriding,{score:overriding.originalScore,overridden:false,overrideReason:""});setOverriding(null);}}/>}
    {pitch&&<PitchModal {...pitch} onClose={()=>setPitch(null)} onReport={()=>report(pitch.match)} notify={notify}/>} 
  </div>;
}

function BuyerRecommendations({buyer,matches,states,compare,showDealToClient,onMatrix,onDeal,onOverride,onPatch,onCompare,onPitch,onReport,notify}:{buyer:BuyerProfile;matches:ExplainableMatch[];states:Record<string,Partial<ExplainableMatch>>;compare:string[];showDealToClient:boolean;onMatrix:(match:ExplainableMatch)=>void;onDeal:(match:ExplainableMatch)=>void;onOverride:(match:ExplainableMatch)=>void;onPatch:(match:ExplainableMatch,next:Partial<ExplainableMatch>)=>void;onCompare:(match:ExplainableMatch)=>void;onPitch:(property:PropertyRecord,match:ExplainableMatch)=>void;onReport:(match:ExplainableMatch)=>void;notify:(message:string)=>void}){
  return <><section className="matching-buyer-hero enhanced"><div><span>ACTIVE BUYER</span><h2>{buyer.name}</h2><p>{buyer.persona} · AED {compact(buyer.budgetMin)}–{compact(buyer.budgetMax)} · {buyer.bedrooms||"Studio"} bed · {buyer.preferredAreas.join(", ")}</p></div><div className="buyer-needs-card"><strong>Needs summary</strong><p>{buyer.needsSummary.keyRequirements || buyer.notes || "Buyer requirements are used to rank matching properties."}</p><small>{buyer.needsSummary.salesAngle || buyer.personaExplanation}</small></div><div><strong>{matches.length}</strong><span>ranked matches</span><small>12 buyer-fit factors</small></div></section>{matches.length?<div className="recommendation-list">{matches.map((match,index)=>{const property=initialProperties.find((item)=>item.id===match.propertyId)!;return <RecommendationCard key={match.id} rank={index+1} property={property} match={match} shortlisted={Boolean(states[match.id]?.shortlisted)} comparing={compare.includes(match.propertyId)} showDealToClient={showDealToClient} onMatrix={()=>onMatrix(match)} onDeal={()=>onDeal(match)} onOverride={()=>onOverride(match)} onCompare={()=>onCompare(match)} onPitch={()=>onPitch(property,match)} onShortlist={()=>{onPatch(match,{shortlisted:!match.shortlisted});notify(match.shortlisted?"Removed from shortlist":"Added to buyer shortlist");}} onHide={()=>onPatch(match,{hidden:true})} onReport={()=>onReport(match)}/>})}</div>:<EmptyMatches/>}</>;
}

function RecommendationCard({rank,property,match,shortlisted,comparing,showDealToClient,onMatrix,onDeal,onOverride,onCompare,onPitch,onShortlist,onHide,onReport}:{rank:number;property:PropertyRecord;match:ExplainableMatch;shortlisted:boolean;comparing:boolean;showDealToClient:boolean;onMatrix:()=>void;onDeal:()=>void;onOverride:()=>void;onCompare:()=>void;onPitch:()=>void;onShortlist:()=>void;onHide:()=>void;onReport:()=>void}){
  return <article className="recommendation-card"><div className="recommendation-rank"><span>#{rank}</span><ScoreRing score={match.score}/>{match.overridden&&<em>Broker override</em>}</div><div className="recommendation-image" style={property.images[0]?{backgroundImage:`url(${property.images[0]})`}:undefined}><span>{property.source}</span>{property.verified&&<b><Check/>Verified</b>}</div><div className="recommendation-copy"><span>{property.neighbourhood} · {property.completionStatus}</span><h3>{property.title}</h3><strong>AED {number.format(property.price)}</strong><p>{property.rooms||"Studio"} bed · {number.format(property.areaSqFt)} sq ft · {property.estimatedYield??"—"}% yield</p><div className="reason-list">{match.reasons.slice(0,3).map((reason)=><span key={reason}><Check/>{reason}</span>)}{match.mismatches.slice(0,1).map((reason)=><span className="warning" key={reason}><AlertTriangle/>{reason}</span>)}</div></div><div className="recommendation-scores"><button onClick={onMatrix}><Target/><span><strong>{match.score}%</strong>Buyer fit matrix</span><ArrowRight/></button><button onClick={onDeal}><Gauge/><span><strong>{match.dealScore}/100 · {match.dealLabel}</strong>Deal score</span>{showDealToClient?<small>Client visible</small>:<small>Hidden</small>}</button><div><button onClick={onShortlist} className={shortlisted?"active":""}><Bookmark/>{shortlisted?"Shortlisted":"Shortlist"}</button><button onClick={onCompare} className={comparing?"active":""}><Columns3/>{comparing?"Comparing":"Compare"}</button><button onClick={onPitch}><MessageCircle/>WhatsApp</button><button onClick={onOverride}><SlidersHorizontal/>Override</button><button onClick={onHide}><EyeOff/>Hide</button><button className="primary-button" onClick={onReport}><FileText/>Report</button></div></div></article>;
}

function PropertyBuyers({property,matches,onMatrix,onOverride,onPatch,onPitch,onReport}:{property:PropertyRecord;matches:Array<{buyer:BuyerProfile;match:ExplainableMatch}>;onMatrix:(match:ExplainableMatch)=>void;onOverride:(match:ExplainableMatch)=>void;onPatch:(match:ExplainableMatch,next:Partial<ExplainableMatch>)=>void;onPitch:(value:{buyer:BuyerProfile;property:PropertyRecord;match:ExplainableMatch})=>void;onReport:(match:ExplainableMatch)=>void}){
  return <><section className="property-match-hero"><div style={property.images[0]?{backgroundImage:`url(${property.images[0]})`}:undefined}/><span><small>PROPERTY-TO-BUYER MATCHING</small><h2>{property.title}</h2><p>{property.neighbourhood} · AED {number.format(property.price)} · {property.rooms||"Studio"} bed · {property.completionStatus}</p></span><ScoreRing score={matches[0]?.match.dealScore??0} label="deal"/></section>{matches.length?<div className="buyer-match-grid">{matches.map(({buyer,match})=><article key={match.id}><header><i>{initials(buyer.name)}</i><span><h3>{buyer.name}</h3><p>{buyer.persona}</p></span><ScoreRing score={match.score}/></header><div className="buyer-match-brief"><span><strong>AED {compact(buyer.budgetMin)}–{compact(buyer.budgetMax)}</strong>Budget</span><span><strong>{buyer.preferredAreas.join(", ")}</strong>Preferred areas</span></div><div className="reason-list">{match.reasons.slice(0,2).map((reason)=><span key={reason}><Check/>{reason}</span>)}{match.mismatches.slice(0,1).map((reason)=><span className="warning" key={reason}><AlertTriangle/>{reason}</span>)}</div><footer><button onClick={()=>onMatrix(match)}>Fit matrix</button><button onClick={()=>onOverride(match)}>Override</button><button onClick={()=>onPatch(match,{hidden:true})}>Hide</button><button onClick={()=>onPitch({buyer,property,match})}><MessageCircle/>Generate pitch</button><button className="primary-button" onClick={()=>onReport(match)}><FileText/>Report</button></footer></article>)}</div>:<EmptyMatches/>}</>;
}

function FitMatrixModal({match,buyer,property,onClose,onReport}:{match:ExplainableMatch;buyer:BuyerProfile;property:PropertyRecord;onClose:()=>void;onReport:()=>void}){
  const [include,setInclude]=useState(true);return <UiModal title="Buyer fit matrix" subtitle={`${buyer.name} × ${property.title}`} onClose={onClose} size="large"><div className="fit-matrix-head"><ScoreRing score={match.score}/><div><strong>{match.score>=85?"Excellent buyer fit":match.score>=70?"Strong fit with trade-offs":"Partial fit requiring broker review"}</strong><p>Every point is traceable to a category. Broker overrides remain visibly labelled.</p></div></div><div className="fit-matrix">{match.matrix.map((item)=><MatrixRow key={item.key} item={item}/>)}</div>{match.overridden&&<div className="override-notice"><SlidersHorizontal/><span><strong>Broker override: {match.score}%</strong>{match.overrideReason}</span></div>}<div className="matrix-report-row"><label><input type="checkbox" checked={include} onChange={(event)=>setInclude(event.target.checked)}/>Include this matrix and mismatch explanations in the client report</label><button className="primary-button" disabled={!include} onClick={onReport}><FileText/>Create report</button></div></UiModal>;
}
function MatrixRow({item}:{item:FitCategory}){return <div className="matrix-row"><span><i>{matrixIcon(item.key)}</i><strong>{item.label}</strong><small>{item.explanation}</small></span><div><em className={item.fit.toLowerCase()}>{item.fit}</em><b>{item.score}/{item.max}</b><u><i style={{width:`${item.score/item.max*100}%`}}/></u></div></div>;}

function DealScoreModal({match,property,visibleToClient,onVisibility,onClose,onReport}:{match:ExplainableMatch;property:PropertyRecord;visibleToClient:boolean;onVisibility:()=>void;onClose:()=>void;onReport:()=>void}){return <UiModal title="Deal score explanation" subtitle={property.title} onClose={onClose} size="large"><div className="deal-score-head"><ScoreRing score={match.dealScore} label="deal"/><div><h3>{match.dealLabel} deal · {match.dealScore}/100</h3><p>{match.dealExplanation}</p></div><button className={visibleToClient?"active":""} onClick={onVisibility}>{visibleToClient?<Gauge/>:<EyeOff/>}{visibleToClient?"Visible in client output":"Hidden from client output"}</button></div><div className="deal-upside-risk"><article><strong>Main upside</strong><p>{match.dealUpside}</p></article><article><strong>Main risk</strong><p>{match.dealRisk}</p></article></div><div className="deal-factor-grid">{match.dealFactors.map((factor)=><div key={factor.label}><span><strong>{factor.label}</strong><small>{factor.explanation}</small></span><b>{factor.score}</b></div>)}</div><div className="form-notice"><AlertTriangle/><span>DLD comparables and transaction history are demo signals until the production data endpoints are connected.</span></div><div className="form-actions"><button className="ghost-button" onClick={onClose}>Close</button><button className="primary-button" onClick={onReport}><FileText/>Add deal score to report</button></div></UiModal>;}

function CompareTray({properties,onClear,onReport}:{properties:PropertyRecord[];onClear:()=>void;onReport:()=>void}){return <div className="matching-compare-tray"><Columns3/><span><strong>{properties.length} properties selected</strong><small>{properties.map((property)=>property.neighbourhood).join(" · ")}</small></span><div>{properties.slice(0,5).map((property)=><em key={property.id}>{property.title}</em>)}</div><button onClick={onClear}>Clear</button><button className="primary-button" onClick={onReport}><FileText/>Comparison report</button></div>;}

function OverrideModal({match,onClose,onSave,onReset}:{match:ExplainableMatch;onClose:()=>void;onSave:(score:number,reason:string)=>void;onReset:()=>void}){const [score,setScore]=useState(match.score);const [reason,setReason]=useState(match.overrideReason);return <UiModal title="Override match score" subtitle={`Calculated score: ${match.originalScore}%`} onClose={onClose}><form className="override-form" onSubmit={(event)=>{event.preventDefault();onSave(score,reason);}}><label>Broker score<strong>{score}%</strong><input type="range" min="0" max="100" value={score} onChange={(event)=>setScore(Number(event.target.value))}/></label><label>Override reason<textarea required value={reason} onChange={(event)=>setReason(event.target.value)} placeholder="Explain why broker knowledge changes the calculated fit…"/></label><div className="form-notice"><SlidersHorizontal/><span>The original calculated score remains available for audit and the override is visibly labelled.</span></div><div className="form-actions">{match.overridden&&<button type="button" className="ghost-button" onClick={onReset}><RotateCcw/>Restore calculated score</button>}<FormActions onCancel={onClose} submitLabel="Save override"/></div></form></UiModal>;}

function PitchModal({buyer,property,match,onClose,onReport,notify}:{buyer:BuyerProfile;property:PropertyRecord;match:ExplainableMatch;onClose:()=>void;onReport:()=>void;notify:(message:string)=>void}){const [pitch,setPitch]=useState(`Hi ${buyer.name.split(" ")[0]}, I found an option in ${property.neighbourhood} that scores ${match.score}% against your brief. ${match.reasons.slice(0,2).join(" ")} The asking price is AED ${number.format(property.price)}. I can send you a concise comparison with the trade-offs if useful.`);return <UiModal title="Buyer pitch" subtitle={`${property.title} → ${buyer.name}`} onClose={onClose}><div className="pitch-modal"><div><Sparkles/><span><strong>Why this pitch works</strong>Uses buyer-fit evidence without making unsupported promises.</span></div><textarea value={pitch} onChange={(event)=>setPitch(event.target.value)}/><div className="form-actions"><button className="ghost-button" onClick={()=>{navigator.clipboard?.writeText(pitch);notify("Pitch copied for WhatsApp or email");}}>Copy pitch</button><button className="primary-button" onClick={onReport}>Create supporting report</button></div></div></UiModal>;}

function ScoreRing({score,label="fit"}:{score:number;label?:string}){return <div className={`score-ring score-${score>=85?"high":score>=65?"medium":"low"}`} style={{"--score":`${score*3.6}deg`} as React.CSSProperties}><span><strong>{score}</strong><small>{label}</small></span></div>;}
function EmptyMatches(){return <div className="matching-empty"><Target/><h3>No matches meet the current filter</h3><p>Lower the minimum score or show more than the best three results.</p></div>;}
function compact(value:number){return value>=1_000_000?`${(value/1_000_000).toFixed(1)}M`:`${Math.round(value/1000)}K`;}
function initials(name:string){return name.split(" ").map((item)=>item[0]).join("").slice(0,2).toUpperCase();}
function matrixIcon(key:string){return key==="school"?<School/>:key==="commute"?<BriefcaseBusiness/>:key==="area"?<MapPin/>:key==="investment"||key==="yield"?<BarChart3/>:<Check/>;}
