"use client";

import { useState } from "react";
import { Activity, Building2, Check, ChevronRight, Clock3, Download, FileText, Filter, Laptop, Lock, LogIn, LogOut, Search, ShieldCheck, Smartphone, UserPlus, Users } from "lucide-react";
import type { AuthSession } from "@/lib/auth";
import type { Workspace } from "@/lib/workspace";
import { backendGuardExample, canAccessPage, pageAccessMap, roleScopeSummary, workspaceRoleOptions, type Role } from "@/lib/rbac";
import { UiModal } from "@/components/ui-modal";

type Props = { workspace: Workspace; session: AuthSession; onLogout: () => void; notify: (message: string) => void };
type AuditEvent = { id: string; action: string; category: string; user: string; date: string; workspace: string; detail: string; icon: string; immutable: true };

const auditEvents: AuditEvent[] = [
  { id: "evt_901", action: "Login", category: "Authentication", user: "Zied Machkena", date: "24 Jun 2026 · 10:42", workspace: "Zied Properties", detail: "Secure session created from Mac · Dubai, AE", icon: "login", immutable: true },
  { id: "evt_900", action: "Buyer created", category: "Buyers", user: "Zied Machkena", date: "24 Jun 2026 · 10:18", workspace: "Zied Properties", detail: "Created buyer profile Omar Al Mansoori", icon: "buyer", immutable: true },
  { id: "evt_899", action: "Property imported", category: "Properties", user: "Maya Rahman", date: "24 Jun 2026 · 09:55", workspace: "Zied Properties", detail: "Bayut JSON · 38 inserted, 4 updated, 3 warnings", icon: "property", immutable: true },
  { id: "evt_898", action: "Report generated", category: "Reports", user: "Zied Machkena", date: "24 Jun 2026 · 09:42", workspace: "Zied Properties", detail: "Marina Vista investment case · prompt v3.2", icon: "report", immutable: true },
  { id: "evt_897", action: "Report exported", category: "Reports", user: "Zied Machkena", date: "24 Jun 2026 · 09:44", workspace: "Zied Properties", detail: "Branded PDF export · rep_001", icon: "report", immutable: true },
  { id: "evt_896", action: "User invited", category: "Access", user: "Zied Machkena", date: "23 Jun 2026 · 16:30", workspace: "Zied Properties", detail: "Invited maya@example.com as Broker / Agent", icon: "invite", immutable: true },
  { id: "evt_895", action: "Branding changed", category: "Workspace", user: "Zied Machkena", date: "23 Jun 2026 · 14:12", workspace: "Zied Properties", detail: "Updated primary colour and report footer", icon: "workspace", immutable: true },
  { id: "evt_894", action: "Buyer deleted", category: "Buyers", user: "Zied Machkena", date: "22 Jun 2026 · 11:08", workspace: "Zied Properties", detail: "Privacy deletion completed · linked reports archived", icon: "buyer", immutable: true },
  { id: "evt_893", action: "Data enriched", category: "Buyers", user: "Rami Haddad", date: "21 Jun 2026 · 15:21", workspace: "Zied Properties", detail: "Consented professional context added to buyer profile", icon: "buyer", immutable: true },
];

export function SecurityEpic({ workspace, session, onLogout, notify }: Props) {
  const [tab, setTab] = useState("Access & isolation");
  const [role, setRole] = useState<Role>(session.user.role);
  const [event, setEvent] = useState<AuditEvent | null>(null);
  const [query, setQuery] = useState("");
  const [category, setCategory] = useState("All events");
  const [otherSessions, setOtherSessions] = useState(["Chrome · iPhone 15 · Dubai, AE"]);
  const visibleEvents = auditEvents.filter((item) => (item.action + item.user + item.detail).toLowerCase().includes(query.toLowerCase()) && (category === "All events" || item.category === category));
  const scope = roleScopeSummary(role);
  return <div className="security-epic module-stack">
    <section className="security-hero"><div><span><ShieldCheck />SECURITY CONTROL CENTRE</span><h2>Workspace access is isolated and role controlled</h2><p>Session, permissions, and audit evidence for <strong>{workspace.name}</strong>.</p></div><div className="security-score"><strong>100%</strong><span>Controls configured</span></div></section>
    <div className="security-tabs">{["Access & isolation", "Sessions", "Audit logs"].map((item) => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}{item === "Audit logs" && <span>{auditEvents.length}</span>}</button>)}</div>
    {tab === "Access & isolation" && <div className="access-layout"><section className="access-main"><div className="section-title"><div><h3>Row-level data security</h3><p>Preview exactly what each role can access</p></div><span className="enforced-badge"><Lock />Enforced</span></div><div className="role-simulator"><label>Simulate role<select value={role} onChange={(e) => setRole(e.target.value as Role)}>{workspaceRoleOptions(workspace.type).map((item) => <option key={item}>{item}</option>)}</select></label><div className="simulated-user"><i>{role === "Owner" ? "ZM" : role === "Admin" ? "AD" : role === "Manager" ? "MG" : role === "Viewer" ? "VW" : "BR"}</i><span><strong>{role} view</strong>Workspace membership resolves access before every query.</span></div></div><div className="scope-grid"><ScopeCard icon={Users} label="Buyers" value={scope.buyers} detail={role === "Broker / Agent" ? "Cannot access another broker’s private buyers" : "Filtered by effective role scope"} /><ScopeCard icon={Building2} label="Properties" value={scope.properties} detail="Private notes remain user-scoped" /><ScopeCard icon={FileText} label="Reports" value={scope.reports} detail="Public links require separate secure tokens" /><ScopeCard icon={ShieldCheck} label="Administration" value={scope.admin ? "Allowed" : "Blocked"} detail={scope.admin ? "Workspace policy and member controls" : "Admin routes return 403 Forbidden"} /></div><RolePolicyPreview role={role} workspace={workspace} /><div className="rls-request"><span>EXAMPLE BACKEND GUARD</span><code>{backendGuardExample("buyers", "buyers.access").join(`\n`)}</code><div><Check />Workspace filter and permission check cannot be removed by the client</div></div></section><aside className="isolation-panel"><div className="isolation-visual"><div className="workspace-vault current"><Lock /><strong>{workspace.name}</strong><span>{workspace.id}</span><small>Current session</small></div><i /><div className="workspace-vault blocked"><Building2 /><strong>Another Agency</strong><span>ws_other_agency</span><small>Access denied</small></div></div><h3>Cross-workspace isolation</h3><p>IDs alone never grant access. Membership and role are checked server-side for every read, write, export, and AI generation.</p><ul><li><Check />Solo broker sees only own workspace</li><li><Check />Team data respects member permissions</li><li><Check />Agency data respects role + assignment</li><li><Check />Cross-workspace queries return no rows</li></ul></aside></div>}
    {tab === "Sessions" && <div className="session-layout"><section className="session-panel"><div className="section-title"><div><h3>Active sessions</h3><p>Devices currently signed into your account</p></div><button onClick={() => { setOtherSessions([]); notify("Other demo sessions signed out"); }}>Sign out other sessions</button></div><div className="session-row current"><i><Laptop /></i><div><strong>{session.device}</strong><p>{session.ipHint}</p><span>Current session · Active now</span></div><em>Current</em></div>{otherSessions.map((device) => <div className="session-row" key={device}><i><Smartphone /></i><div><strong>{device}</strong><p>Last active 2 hours ago</p><span>Session ID ses_mobile_demo</span></div><button onClick={() => setOtherSessions([])}>Revoke</button></div>)}</section><aside className="session-security-card"><ShieldCheck /><h3>Secure session</h3><div><span>Transport</span><strong>TLS required</strong></div><div><span>Token storage</span><strong>HTTP-only secure cookie</strong></div><div><span>Rotation</span><strong>Refresh token rotated</strong></div><div><span>Expiry</span><strong>8 hours · idle timeout</strong></div><div><span>CSRF</span><strong>SameSite + token validation</strong></div><button className="danger-outline" onClick={onLogout}><LogOut />Log out this session</button></aside></div>}
    {tab === "Audit logs" && <div className="audit-stack"><div className="audit-summary"><div><Activity /><span><strong>{auditEvents.length}</strong>Recorded events</span></div><div><Lock /><span><strong>Immutable</strong>Events cannot be edited</span></div><div><Clock3 /><span><strong>7 years</strong>Proposed retention</span></div><button onClick={() => notify("Audit CSV export prepared")}><Download />Export CSV</button></div><div className="audit-toolbar"><div><Search /><input placeholder="Search action, user, or detail…" value={query} onChange={(e) => setQuery(e.target.value)} /></div><label><Filter /><select value={category} onChange={(e) => setCategory(e.target.value)}><option>All events</option><option>Authentication</option><option>Buyers</option><option>Properties</option><option>Reports</option><option>Access</option><option>Workspace</option></select></label></div><section className="audit-table"><div className="audit-head"><span>Event</span><span>User</span><span>Date & time</span><span>Workspace</span><span>Integrity</span><span /></div>{visibleEvents.map((item) => <button className="audit-row" key={item.id} onClick={() => setEvent(item)}><span><AuditIcon kind={item.icon} /><b>{item.action}<small>{item.detail}</small></b></span><span>{item.user}</span><span>{item.date}</span><span>{item.workspace}</span><span><Lock />Immutable</span><ChevronRight /></button>)}</section></div>}
    {event && <UiModal title={event.action} subtitle={`Audit event ${event.id}`} onClose={() => setEvent(null)}><div className="audit-detail"><div className="audit-detail-lock"><Lock /><span><strong>Immutable event</strong>This record can be viewed and exported but never edited or deleted.</span></div>{[["User", event.user], ["Date and time", event.date], ["Workspace", `${event.workspace} · ${workspace.id}`], ["Category", event.category], ["Detail", event.detail], ["Request ID", "req_01J14DX7M9Q2"], ["Integrity hash", "sha256:8b6f…2d91"]].map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div></UiModal>}
  </div>;
}

function RolePolicyPreview({ role, workspace }: { role: Role; workspace: Workspace }) {
  const policies = pageAccessMap.map((policy) => ({ ...policy, access: canAccessPage(role, workspace.type, policy.page) }));
  return <section className="role-policy-preview">
    <div className="section-title compact"><div><h3>Page permission map</h3><p>Every route checks workspace membership + active role before rendering.</p></div></div>
    <div className="role-policy-grid">{policies.map((policy) => <div key={policy.page} className={policy.access.allowed ? "allowed" : "blocked"}><span>{policy.page}</span><strong>{policy.access.allowed ? "Allowed" : "Blocked"}</strong><small>{policy.permission}</small></div>)}</div>
  </section>;
}

function ScopeCard({ icon: Icon, label, value, detail }: { icon: typeof Users; label: string; value: string; detail: string }) { return <article><i><Icon /></i><span>{label}</span><strong>{value}</strong><p>{detail}</p></article>; }
function AuditIcon({ kind }: { kind: string }) { const Icon = kind === "login" ? LogIn : kind === "invite" ? UserPlus : kind === "property" || kind === "workspace" ? Building2 : kind === "report" ? FileText : Users; return <i><Icon /></i>; }
